apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-deployment
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: k8spublisher
          image: k8spublisher:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: minikube
